#@ load("@ytt:data", "data")

#@ def buildWorkloadTarget():
#@ profiles = ""
#@ if data.values.serviceType == "web":
  apiVersion: serving.knative.dev/v1
  kind: Service
#@ else:
  apiVersion: apps/v1
  kind: Deployment
#@ end
  name: #@ data.values.name
#@ end

---
apiVersion: servicebinding.io/v1
kind: ServiceBinding
metadata:
  name: #@ data.values.name + '-cache'
spec:
  name: cache
  replicas: 1
  service:
    apiVersion: bitnami.caching.tanzu.vmware.com/v1alpha1
    kind: RedisCluster
    name: #@ data.values.redisName
  workload: #@ buildWorkloadTarget()
