#@ load("@ytt:data", "data")

#@ def getWorkloadType():
#@ if data.values.useWebType == "yes":
#@   return "web"
#@ else:
#@   return "server"
#@ end
#@ end

#@ def buildParams(containerPort,keepAlive):
#@ if data.values.useWebType == "yes":  
  - name: annotations
    value: 
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
      autoscaling.knative.dev/minScale: "1"          
#@ else:
  - name: ports
    value:
    - port: 80
      containerPort: #@ containerPort
      name: http
#@ end
#@ end

#@ def buildDBProfileEnv():
#@ profiles = ""
#@ if data.values.dbType == "mysql":
#@ profiles = "mysql"
#@ else:
#@ profiles = "postgres"
#@ end
  - name: spring_profiles_active
    value: #@ profiles
#@ end

#@ def useTestScan():
#@ if data.values.useTestScan == "yes":
#@   return "true"
#@ else:
#@   return "false"
#@ end
#@ end

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-api-gateway
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()   
    apps.tanzu.vmware.com/auto-configure-actuators: "true" 
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"  
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"       
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-api-gateway
    
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: #@ getWorkloadType()
    app.kubernetes.io/part-of: where-for-dinner-search
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()  
    apps.tanzu.vmware.com/auto-configure-actuators: "true"  
spec:
  env: #@ buildDBProfileEnv()
  params: #@ buildParams(8080,True)
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.rabbitMQName
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.dbName
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"       
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-search
---

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-proc
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: #@ getWorkloadType()
    app.kubernetes.io/part-of: where-for-dinner-search-proc
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()  
    apps.tanzu.vmware.com/auto-configure-actuators: "true"  
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"       
  params: #@ buildParams(8080,False)
  env: 
  - name: spring_profiles_active
    value: crawler,redis
  serviceClaims: 
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.rabbitMQName  
  - name: redis
    ref:
      apiVersion: v1
      kind: Secret
      name: #@ data.values.redisName + "-redis-secret"
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m" 
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-search-proc
    
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-notify
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: #@ getWorkloadType()
    app.kubernetes.io/part-of: where-for-dinner-notify
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()   
    apps.tanzu.vmware.com/auto-configure-actuators: "true"       
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"           
  params: #@ buildParams(8080,False)
  serviceClaims: 
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.rabbitMQName    
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m" 
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-notify
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-availability
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: #@ getWorkloadType()
    app.kubernetes.io/part-of: where-for-dinner-availability
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()  
    apps.tanzu.vmware.com/auto-configure-actuators: "true"    
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"             
  env: #@ buildDBProfileEnv()
  params: #@ buildParams(8080,True)
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.rabbitMQName    
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.dbName   
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1.5"  
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-availability

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-ui
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: #@ getWorkloadType()
    app.kubernetes.io/part-of: where-for-dinner-ui
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()    
spec:
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: dist
  params: #@ buildParams(8080,True) 
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"  
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-ui
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-crawler
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-crawler
    apps.tanzu.vmware.com/has-tests: #@ useTestScan()  
    apps.tanzu.vmware.com/auto-configure-actuators: "true"    
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"      
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-crawler
